//컨텐츠(토픽) 전용 슬라이스
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';
import { getTopics, type Topic as ContentCardType } from '@/services/api/topicApi';
import { getCommentCards } from '@/services/api/commentApi';

export type ContentState = {
  loading: boolean;
  contents: ContentCardType[];
  error?: string | null;
}

const initialState: ContentState = {
  loading: false,
  contents: [],
  error: null,
}

export const fetchContentsThunk = createAsyncThunk(
  'content/fetch',
  async (_, { rejectWithValue }) => {
    try {
      const topicsList = await getTopics();
      const data = topicsList.list;
      
      // 코멘트 데이터를 가져와서 overallRating 계산
      try {
        const comments = await getCommentCards();
        
        // 각 컨텐츠의 overallRating을 코멘트 평균으로 계산
        const contentsWithRating = data.map(content => {
          const relatedComments = comments.filter(c => c.contentId === content.id);
          
          if (relatedComments.length === 0) {
            return { ...content, overallRating: 0 };  // 코멘트가 없으면 0
          }
          
          const avgRating = relatedComments.reduce((sum, c) => sum + c.rating, 0) / relatedComments.length;
          return { ...content, overallRating: Number(avgRating.toFixed(1)) };
        });
        
        return contentsWithRating;
      } catch (commentError) {
        // 코멘트 API 실패해도 컨텐츠는 반환
        console.warn('Comment API 호출 실패 (overallRating 계산 스킵):', commentError);
        return data;
      }
    } catch (error) {
      console.error('Content API 호출 실패:', error);
      const tempData: ContentCardType[] = [
        {
          id: 1,
          title: '다 이루어질 지니',
          englishTitle: 'Everything Will Come True',
          images: ['https://picsum.photos/900/1600?random=1'],
          runtime: '120분',
          ageRating: '15',
          releaseDate: '2025-01-15',
          year: '2025',
          category: '영화',
          country: '한국',
          genre: '액션',
          synopsis: '케이팝 슈퍼스타 루미, 미라, 조이. 매진을 기록하는 대형 스타디움 공연이 없을 때면 이들은 또 다른 활동에 나선다. 바로 비밀 능력을 이용해 팬들을 초자연적 위협으로부터 보호하는 것.',
          overallRating: 4.5,
          imageUrl: 'https://picsum.photos/900/1600?random=1',
          createdAt: '2024-12-01',
          updatedAt: '2024-12-01',
        },
        {
          id: 2,
          title: '사마귀',
          englishTitle: 'Mantis',
          images: ['https://picsum.photos/300/400?random=2'],
          runtime: '110분',
          ageRating: '15',
          releaseDate: '2025-02-01',
          year: '2025',
          category: '영화',
          country: '한국',
          genre: '액션',
          synopsis: '2025년 대한민국, 더 화끈하게! 액션과 스릴이 가득한 새로운 영화가 등장한다. 예측 불가능한 스토리와 강렬한 액션으로 관객들을 사로잡을 것이다.',
          overallRating: 4.0,
          imageUrl: 'https://picsum.photos/300/400?random=2',
          createdAt: '2024-12-01',
          updatedAt: '2024-12-01',
        },
        {
          id: 3,
          title: '야당',
          englishTitle: 'Opposition',
          images: ['https://picsum.photos/300/400?random=3'],
          runtime: '60분',
          ageRating: '15',
          releaseDate: '2024-03-01',
          year: '2024',
          category: '드라마',
          country: '한국',
          genre: '정치',
          synopsis: '정치적 갈등과 권력의 암투가 펼쳐지는 드라마. 현실적인 정치 상황을 그려내며 시청자들에게 깊은 여운을 남기는 작품이다.',
          overallRating: 4.8,
          imageUrl: 'https://picsum.photos/300/400?random=3',
          createdAt: '2024-02-01',
          updatedAt: '2024-02-01',
        },
        {
          id: 4,
          title: '토르: 천둥의 신',
          englishTitle: 'Thor',
          images: ['https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg'],
          runtime: '115분',
          ageRating: '12',
          releaseDate: '2004-05-01',
          year: '2004',
          category: '영화',
          country: '미국',
          genre: '판타지',
          synopsis: '아스가르드의 천둥의 신 토르가 지구로 추방되어 인간 세계에서 신으로서의 긍지와 능력을 다시 찾아가는 과정을 그린 판타지 액션.',
          overallRating: 4.0,
          imageUrl: 'https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
          createdAt: '2004-04-01',
          updatedAt: '2004-04-01',
        },
        {
          id: 5,
          title: '인터스텔라',
          englishTitle: 'Interstellar',
          images: ['https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'],
          runtime: '169분',
          ageRating: '12',
          releaseDate: '2014-11-06',
          year: '2014',
          category: '영화',
          country: '미국',
          genre: 'SF',
          synopsis: '지구가 위기에 처한 가운데, 우주를 탐험하는 과학자 팀이 새로운 행성을 찾아 인류를 구하기 위한 모험을 떠나는 SF 드라마.',
          overallRating: 4.7,
          imageUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
          createdAt: '2014-10-01',
          updatedAt: '2014-10-01',
        },
        {
          id: 6,
          title: '다크 나이트',
          englishTitle: 'The Dark Knight',
          images: ['https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg'],
          runtime: '152분',
          ageRating: '15',
          releaseDate: '2008-07-18',
          year: '2008',
          category: '영화',
          country: '미국',
          genre: '액션',
          synopsis: '배트맨이 조커의 완전한 무정부주의적 테러에 맞서 고담시티를 지키기 위한 치열한 싸움을 펼치는 슈퍼히어로 액션.',
          overallRating: 4.9,
          imageUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
          createdAt: '2008-06-01',
          updatedAt: '2008-06-01',
        },
        {
          id: 7,
          title: '인셉션',
          englishTitle: 'Inception',
          images: ['https://picsum.photos/300/400?random=101'],
          runtime: '148분',
          ageRating: '12',
          releaseDate: '2010-07-22',
          year: '2010',
          category: '영화',
          country: '미국',
          genre: 'SF',
          synopsis: '꿈 속의 꿈 속으로 들어가 상대의 무의식에 아이디어를 심는 기술, 인셉션을 다룬 미래적 SF 스릴러 영화.',
          overallRating: 4.6,
          imageUrl: 'https://picsum.photos/300/400?random=101',
          createdAt: '2010-06-01',
          updatedAt: '2010-06-01',
        },
        {
          id: 8,
          title: '어벤져스',
          englishTitle: 'The Avengers',
          images: ['https://picsum.photos/300/400?random=102'],
          runtime: '143분',
          ageRating: '12',
          releaseDate: '2012-05-04',
          year: '2012',
          category: '영화',
          country: '미국',
          genre: '액션',
          synopsis: '아이언맨, 토르, 헐크, 캡틴 아메리카 등의 히어로들이 뭉쳐 세계를 구하기 위해 맞서는 역대급 액션 블록버스터.',
          overallRating: 4.0,
          imageUrl: 'https://picsum.photos/300/400?random=102',
          createdAt: '2012-04-01',
          updatedAt: '2012-04-01',
        },
        {
          id: 9,
          title: '기생충',
          englishTitle: 'Parasite',
          images: ['https://picsum.photos/300/400?random=103'],
          runtime: '132분',
          ageRating: '15',
          releaseDate: '2019-05-30',
          year: '2019',
          category: '영화',
          country: '한국',
          genre: '스릴러',
          synopsis: '반지하 주택에 살던 기택 가족이 상류층 박 사장 집에 취업하며 벌어지는 계급 간 갈등을 담은 블랙코미디 스릴러.',
          overallRating: 4.8,
          imageUrl: 'https://picsum.photos/300/400?random=103',
          createdAt: '2019-05-01',
          updatedAt: '2019-05-01',
        },
        {
          id: 10,
          title: '타이타닉',
          englishTitle: 'Titanic',
          images: ['https://picsum.photos/300/400?random=104'],
          runtime: '194분',
          ageRating: '12',
          releaseDate: '1997-12-19',
          year: '1997',
          category: '영화',
          country: '미국',
          genre: '로맨스',
          synopsis: '1912년 타이타닉 호에서 만난 상류층 레이디 로즈와 하층민 출신 잭의 금지된 사랑을 그린 로맨스 재난 영화.',
          overallRating: 4.4,
          imageUrl: 'https://picsum.photos/300/400?random=104',
          createdAt: '1997-11-01',
          updatedAt: '1997-11-01',
        },
        {
          id: 11,
          title: '겨울왕국',
          englishTitle: 'Frozen',
          images: ['https://picsum.photos/300/400?random=105'],
          runtime: '102분',
          ageRating: 'all',
          releaseDate: '2013-11-27',
          year: '2013',
          category: '애니메이션',
          country: '미국',
          genre: '판타지',
          synopsis: '마법의 얼음 힘을 가진 엘사의 실수로 왕국이 겨울에 얼어붙자, 여동생 안나와 함께 왕국을 구하기 위해 떠나는 모험 이야기.',
          overallRating: 4.5,
          imageUrl: 'https://picsum.photos/300/400?random=105',
          createdAt: '2013-10-01',
          updatedAt: '2013-10-01',
        },
        {
          id: 12,
          title: '올드보이',
          englishTitle: 'Oldboy',
          images: ['https://picsum.photos/300/400?random=106'],
          runtime: '120분',
          ageRating: '18',
          releaseDate: '2003-11-21',
          year: '2003',
          category: '영화',
          country: '한국',
          genre: '스릴러',
          synopsis: '15년간 감금된 오대수가 풀려난 후 복수를 위해 자신을 가둔 자를 찾아가는 강렬한 복수 스릴러.',
          overallRating: 4.7,
          imageUrl: 'https://picsum.photos/300/400?random=106',
          createdAt: '2003-10-01',
          updatedAt: '2003-10-01',
        },
        {
          id: 13,
          title: '매트릭스',
          englishTitle: 'The Matrix',
          images: ['https://picsum.photos/300/400?random=107'],
          runtime: '136분',
          ageRating: '15',
          releaseDate: '1999-03-31',
          year: '1999',
          category: '영화',
          country: '미국',
          genre: 'SF',
          synopsis: '컴퓨터 프로그래머 네오가 현실이 사실은 컴퓨터 시뮬레이션 매트릭스라는 것을 깨닫고 인간을 구하기 위해 싸우는 SF 액션.',
          overallRating: 4.8,
          imageUrl: 'https://picsum.photos/300/400?random=107',
          createdAt: '1999-02-01',
          updatedAt: '1999-02-01',
        },
        {
          id: 14,
          title: '위대한 개츠비',
          englishTitle: 'The Great Gatsby',
          images: ['https://picsum.photos/300/400?random=108'],
          runtime: '143분',
          ageRating: '12',
          releaseDate: '2013-05-10',
          year: '2013',
          category: '영화',
          country: '미국',
          genre: '드라마',
          synopsis: '1920년대 재즈 시대를 배경으로 한 부와 사랑, 허영심을 그린 F. 스콧 피츠제럴드의 소설 원작 영화.',
          overallRating: 4.2,
          imageUrl: 'https://picsum.photos/300/400?random=108',
          createdAt: '2013-04-01',
          updatedAt: '2013-04-01',
        },
        {
          id: 15,
          title: '라라랜드',
          englishTitle: 'La La Land',
          images: ['https://picsum.photos/300/400?random=109'],
          runtime: '128분',
          ageRating: '12',
          releaseDate: '2016-12-16',
          year: '2016',
          category: '영화',
          country: '미국',
          genre: '뮤지컬',
          synopsis: '할리우드에서 배우와 음악가를 꿈꾸는 젊은 남녀의 사랑과 성공을 그린 뮤지컬 영화.',
          overallRating: 4.6,
          imageUrl: 'https://picsum.photos/300/400?random=109',
          createdAt: '2016-11-01',
          updatedAt: '2016-11-01',
        },
        {
          id: 16,
          title: '범죄도시',
          englishTitle: 'The Outlaws',
          images: ['https://picsum.photos/300/400?random=110'],
          runtime: '121분',
          ageRating: '15',
          releaseDate: '2017-10-03',
          year: '2017',
          category: '영화',
          country: '한국',
          genre: '액션',
          synopsis: '2004년 서울 용산구에서 벌어진 중국 조폭 조직과 한국 경찰 간의 실화를 바탕으로 한 액션 영화.',
          overallRating: 4.3,
          imageUrl: 'https://picsum.photos/300/400?random=110',
          createdAt: '2017-09-01',
          updatedAt: '2017-09-01',
        },
        {
          id: 17,
          title: '해리포터와 마법사의 돌',
          englishTitle: 'Harry Potter and the Philosopher\'s Stone',
          images: ['https://picsum.photos/300/400?random=111'],
          runtime: '152분',
          ageRating: 'all',
          releaseDate: '2001-11-16',
          year: '2001',
          category: '영화',
          country: '영국',
          genre: '판타지',
          synopsis: '마법사가 된 해리 포터가 호그와트 마법학교에서 친구들과 함께 어둠의 마법사 볼드모트와 맞서는 판타지 영화.',
          overallRating: 4.4,
          imageUrl: 'https://picsum.photos/300/400?random=111',
          createdAt: '2001-10-01',
          updatedAt: '2001-10-01',
        },
        {
          id: 18,
          title: '트랜스포머',
          englishTitle: 'Transformers',
          images: ['https://picsum.photos/300/400?random=112'],
          runtime: '144분',
          ageRating: '12',
          releaseDate: '2007-07-11',
          year: '2007',
          category: '영화',
          country: '미국',
          genre: 'SF',
          synopsis: '외계 로봇 오토봇과 디셉티콘의 전쟁에 휘말린 소년 샘의 이야기를 그린 SF 액션 블록버스터.',
          overallRating: 4.1,
          imageUrl: 'https://picsum.photos/300/400?random=112',
          createdAt: '2007-06-01',
          updatedAt: '2007-06-01',
        },
        {
          id: 19,
          title: '부산행',
          englishTitle: 'Train to Busan',
          images: ['https://picsum.photos/300/400?random=113'],
          runtime: '118분',
          ageRating: '15',
          releaseDate: '2016-07-20',
          year: '2016',
          category: '영화',
          country: '한국',
          genre: '좀비',
          synopsis: '좀비 바이러스가 퍼진 가운데 부산행 KTX 열차에 탑승한 승객들이 살아남기 위해 싸우는 재난 스릴러.',
          overallRating: 4.5,
          imageUrl: 'https://picsum.photos/300/400?random=113',
          createdAt: '2016-06-01',
          updatedAt: '2016-06-01',
        },
        {
          id: 20,
          title: '어바웃 타임',
          englishTitle: 'About Time',
          images: ['https://picsum.photos/300/400?random=114'],
          runtime: '123분',
          ageRating: '12',
          releaseDate: '2013-11-28',
          year: '2013',
          category: '영화',
          country: '영국',
          genre: '로맨스',
          synopsis: '시간 여행 능력을 가진 남자가 사랑하는 여자를 만나기 위해 시간을 되돌리는 로맨틱 코미디.',
          overallRating: 4.3,
          imageUrl: 'https://picsum.photos/300/400?random=114',
          createdAt: '2013-10-01',
          updatedAt: '2013-10-01',
        },
        {
          id: 21,
          title: '어벤져스: 엔드게임',
          englishTitle: 'Avengers: Endgame',
          images: ['https://picsum.photos/300/400?random=115'],
          runtime: '181분',
          ageRating: '12',
          releaseDate: '2019-04-26',
          year: '2019',
          category: '영화',
          country: '미국',
          genre: '액션',
          synopsis: '타노스의 스냅으로 사라진 절반의 생명체를 되돌리기 위해 어벤져스가 과거로 돌아가 싸우는 마블 시네마틱 유니버스의 대단원.',
          overallRating: 4.7,
          imageUrl: 'https://picsum.photos/300/400?random=115',
          createdAt: '2019-03-01',
          updatedAt: '2019-03-01',
        },
        {
          id: 22,
          title: '쇼생크 탈출',
          englishTitle: 'The Shawshank Redemption',
          images: ['https://picsum.photos/300/400?random=116'],
          runtime: '142분',
          ageRating: '15',
          releaseDate: '1994-09-23',
          year: '1994',
          category: '영화',
          country: '미국',
          genre: '드라마',
          synopsis: '무죄임에도 불구하고 쇼생크 교도소에 갇힌 앤디가 20년간의 수감 생활 끝에 탈출을 시도하는 감동적인 드라마.',
          overallRating: 4.9,
          imageUrl: 'https://picsum.photos/300/400?random=116',
          createdAt: '1994-08-01',
          updatedAt: '1994-08-01',
        },
        {
          id: 23,
          title: '그래비티',
          englishTitle: 'Gravity',
          images: ['https://picsum.photos/300/400?random=117'],
          runtime: '91분',
          ageRating: '12',
          releaseDate: '2013-10-17',
          year: '2013',
          category: '영화',
          country: '미국',
          genre: 'SF',
          synopsis: '우주 임무 중 우주선이 파괴되어 고립된 우주비행사가 지구로 돌아오기 위해 생존을 시도하는 SF 스릴러.',
          overallRating: 4.4,
          imageUrl: 'https://picsum.photos/300/400?random=117',
          createdAt: '2013-09-01',
          updatedAt: '2013-09-01',
        },
        {
          id: 24,
          title: '범죄와의 전쟁',
          englishTitle: 'Nameless Gangster',
          images: ['https://picsum.photos/300/400?random=118'],
          runtime: '133분',
          ageRating: '18',
          releaseDate: '2012-02-02',
          year: '2012',
          category: '영화',
          country: '한국',
          genre: '범죄',
          synopsis: '1980년대 부산에서 세관 공무원 출신이 조직의 보스로 성장하는 과정을 그린 범죄 액션 영화.',
          overallRating: 4.6,
          imageUrl: 'https://picsum.photos/300/400?random=118',
          createdAt: '2012-01-01',
          updatedAt: '2012-01-01',
        },
        {
          id: 25,
          title: '토이 스토리',
          englishTitle: 'Toy Story',
          images: ['https://picsum.photos/300/400?random=119'],
          runtime: '81분',
          ageRating: 'all',
          releaseDate: '1995-11-22',
          year: '1995',
          category: '애니메이션',
          country: '미국',
          genre: '판타지',
          synopsis: '주인공 앤디의 장난감들이 살아있는 것처럼 움직이며 벌어지는 모험을 그린 픽사 애니메이션 영화.',
          overallRating: 4.5,
          imageUrl: 'https://picsum.photos/300/400?random=119',
          createdAt: '1995-10-01',
          updatedAt: '1995-10-01',
        },
        {
          id: 26,
          title: '맨인블랙',
          englishTitle: 'Men in Black',
          images: ['https://picsum.photos/300/400?random=120'],
          runtime: '98분',
          ageRating: '12',
          releaseDate: '1997-07-02',
          year: '1997',
          category: '영화',
          country: '미국',
          genre: 'SF',
          synopsis: '지구에 거주하는 외계인을 감시하고 관리하는 비밀 기관의 요원들이 외계인 범죄를 막는 SF 코미디 액션.',
          overallRating: 4.2,
          imageUrl: 'https://picsum.photos/300/400?random=120',
          createdAt: '1997-06-01',
          updatedAt: '1997-06-01',
        },
        {
          id: 27,
          title: '극한직업',
          englishTitle: 'Extreme Job',
          images: ['https://picsum.photos/300/400?random=121'],
          runtime: '111분',
          ageRating: '12',
          releaseDate: '2019-01-23',
          year: '2019',
          category: '영화',
          country: '한국',
          genre: '코미디',
          synopsis: '마약 조직을 잡기 위해 치킨집을 운영하며 수사하던 형사들이 의도치 않게 치킨집이 대박나면서 벌어지는 코미디.',
          overallRating: 4.4,
          imageUrl: 'https://picsum.photos/300/400?random=121',
          createdAt: '2019-01-01',
          updatedAt: '2019-01-01',
        },
        {
          id: 28,
          title: '월-E',
          englishTitle: 'WALL-E',
          images: ['https://picsum.photos/300/400?random=122'],
          runtime: '98분',
          ageRating: 'all',
          releaseDate: '2008-06-27',
          year: '2008',
          category: '애니메이션',
          country: '미국',
          genre: 'SF',
          synopsis: '쓰레기로 뒤덮인 지구에서 마지막 남은 로봇 월-E가 우주선에 탑승한 이브를 만나 인류를 구하는 SF 애니메이션.',
          overallRating: 4.6,
          imageUrl: 'https://picsum.photos/300/400?random=122',
          createdAt: '2008-05-01',
          updatedAt: '2008-05-01',
        },
        {
          id: 29,
          title: '신과함께-인과 연',
          englishTitle: 'Along With the Gods: The Two Worlds',
          images: ['https://picsum.photos/300/400?random=123'],
          runtime: '139분',
          ageRating: '12',
          releaseDate: '2017-12-20',
          year: '2017',
          category: '영화',
          country: '한국',
          genre: '판타지',
          synopsis: '사후 세계에서 7개의 지옥 재판을 받는 화재 구조원의 이야기를 그린 판타지 영화.',
          overallRating: 4.3,
          imageUrl: 'https://picsum.photos/300/400?random=123',
          createdAt: '2017-11-01',
          updatedAt: '2017-11-01',
        },
        {
          id: 30,
          title: '레옹',
          englishTitle: 'Léon: The Professional',
          images: ['https://picsum.photos/300/400?random=124'],
          runtime: '110분',
          ageRating: '18',
          releaseDate: '1994-09-14',
          year: '1994',
          category: '영화',
          country: '프랑스',
          genre: '액션',
          synopsis: '프로페셔널 킬러 레옹이 가족이 모두 살해당한 12세 소녀 마틸다를 구하고 자신의 복수를 도와달라는 그녀의 요청을 받아들이는 액션 드라마.',
          overallRating: 4.7,
          imageUrl: 'https://picsum.photos/300/400?random=124',
          createdAt: '1994-08-01',
          updatedAt: '1994-08-01',
        },
      ];
      return tempData;
    }
  }
);

const contentSlice = createSlice({
  name: 'content',
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder
      .addCase(fetchContentsThunk.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchContentsThunk.fulfilled, (state, action: PayloadAction<ContentCardType[]>) => {
        state.loading = false;
        state.contents = action.payload;
      })
      .addCase(fetchContentsThunk.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message || 'Failed to fetch contents';
        if (action.payload) {
          state.contents = action.payload as ContentCardType[];
        }
      });
  },
});

export default contentSlice.reducer;

